### ISSUE TITLE
Does this plugin work / is it maintained?

### ISSUE THREAD

**Issue by martinstark** [panekj/lapce-typescript#12]
I've tried to find out of this plugin still works or is maintained. I've been unble to get it to work. I have typescript and typescript-language-server installed through distro package manager, they are available in path. I've tried setting the explicit path to `usr/bin/typescript-language-server` without success.

typescript 5.0.2
typescript-language-server 3.3.0

Selecting "go to definition" and the like does nothing. No indexing seems to run.

**Comment by avrame** [comment]
I am also unable to get this plugin working. Tried the same things as @martinstark : added TLS .to PATH and also tried the explicit path

**Comment by panekj** [comment]
> is it maintained?

is it not?

**Comment by panekj** [comment]
> I've been unble to get it to work.

Plugins are still experimental and will not work always

**Comment by martinstark** [comment]
> > is it maintained?
> 
> is it not?

Given multiple issue reports on the plugin not working and an open PR that tries to fix some aspect of the initialization, and it not working for me and the other guy in this thread, I think it's a fair question

**Comment by panekj** [comment]
that PR doesn't fix anything

**Comment by martinstark** [comment]
Is there a way for us to provide you with debug data on why this plugin can't initialize with lapce, or is unable to communicate with the lsp?

**Comment by panekj** [comment]
I don't need any data to debug it, it's also not broken by itself and the root cause is external.

**Comment by martinstark** [comment]
> the root cause is external

Would you care to share more details here? Does ts lsp version matter? Lapce version? Is it more appropriate to report this to volt or lapce main repo?

**Comment by panekj** [comment]
As I mentioned earlier it's external issue, not related to anything in Lapce or LSP server.

**Comment by martinstark** [comment]
Would you care to share more details here on what those external issues are?

I don't think the intention of Lapce and its plugins is to only work on certain operating system setups or hardware, making me think it's a problem that needs to be solved "internally". Since there are plenty of other LSPs that do work in other text editors and IDEs, I can't even start to guess what "external" problems may be the cause here.
