### ISSUE TITLE
Which path to put in serverPath?

### ISSUE THREAD

**Issue by sawa-ko** [panekj/lapce-typescript#4]
I currently set the following routes but it does not work for me:

![image](https://user-images.githubusercontent.com/56084970/195732063-a8886976-3cc8-4909-8759-7ba6bde9078a.png)

![image](https://user-images.githubusercontent.com/56084970/195732144-c175bcc0-87e7-4c66-a8ec-52996a01b0b7.png)

**Comment by snuffyDev** [comment]
Using the directory in the second picture, verify if there’s a ‘typescript-language-server.cmd’ if there is, use that file. I wasn’t able to get it working until I added “.cmd”
