### ISSUE TITLE
Doesn't run with typescript-language-server latest version

### ISSUE THREAD

**Issue by EduardoMejiaL** [panekj/lapce-typescript#9]
Hi, I tried to make the plugin works for hours and I only got a partial completion (the dropdown menu of suggestions blinks) and I had to make some tweaks to make it work.

I have downgrade my global `typescript-language-server` package to 2.0.0 and everything works now.

It should be nice if this information is contained in the README file.

Thanks

**Comment by ystyle** [comment]
Thanks, it works
```
npm i --global typescript-language-server@2 typescript
```
